name: hipchat-jz
version: 4.29.4.1662-1
summary: Group chat, video chat, and screen sharing
description: |
  Group chat, video chat, and screen sharing

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode

apps:
  hipchat:
    command: desktop-launch $SNAP/opt/HipChat4/bin/HipChat4
    plugs: [x11, opengl, pulseaudio, alsa, camera, hardware-observe, network, network-bind, network-observe, home]

parts:
  hipchat4:
    plugin: nil
    stage-packages:
      - hipchat4
      - gnome-themes-standard
      - libqt5libqgtk2
      - gtk2-engines-pixbuf
      - libpng12-0
      - libnss3
    prime:
      - -usr/include
      - -usr/share/apport
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/libthai
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
      - -var
    after:
      - desktop-qt5
  
  desktop-qt5:
    prime:
      - -usr/include
      - -usr/share/apport
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/libthai
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
      - -var
